language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t lloecher5/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lloecher5/docker-react npm run test
